### PR TITLE
CTCP-3706: Add requested document type to service and connector

### PR DESCRIPTION
**Pull request by Reece-Carruthers**

### CODE REVIEW

**Comment by Reece-Carruthers** [comment]
image

**Comment by Reece-Carruthers** [comment]
rebuild

**Comment by Reece-Carruthers** [comment]
rebuild

**Comment by Reece-Carruthers** [comment]
rebuild

**Review by jackheslop96 — APPROVED** [review]

**Review by jackheslop96 — APPROVED** [review]

**Pull request merged**
